[package]
name = "rust_tcp_protobuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simplelog = "0.12.0"
protobuf = "2"
tinyset = "0.4.10"

[build-dependencies]
protoc-rust = "2.0"
